apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: golias-general-metrics-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: golias_general_metrics_topic
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  
