apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-grafana
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-grafana
  data:
    - secretKey: password
      remoteRef:
        key: grafana
        property: admin-password
