apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
  data:
    - secretKey: admin-token
      remoteRef:
        key: vaultwarden
        property: admin-token
