repositories:
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: cosmo
    url: oci://ghcr.io/wundergraph/cosmo/helm
    oci: true

releases:
  - name: tailscale-operator
    namespace: tailscale
    createNamespace: true
    chart: tailscale/tailscale-operator
    values:
      - apps/tailscale/values.yaml

  - name: strimzi-kafka-operator
    namespace: kafka
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    values:
      - apps/kafka/values.yaml

  - name: cosmo
    namespace: cosmo
    createNamespace: true
    chart: cosmo/cosmo
    values:
      - apps/cosmo/values.yaml
