apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openobserve-root
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: openobserve-root
  data:
    - secretKey: ZO_ROOT_USER_EMAIL
      remoteRef:
        key: openobserve
        property: root-email
    - secretKey: ZO_ROOT_USER_PASSWORD
      remoteRef:
        key: openobserve
        property: root-password
