apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-backend-ingress
  namespace: f1
spec:
  rules:
    - host: f1-api.golias.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: f1-backend-service
                port:
                  number: 8080