apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmo-router
  namespace: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmo-router
  template:
    metadata:
      labels:
        app: cosmo-router
    spec:
      containers:
        - name: cosmo-router
          image: ghcr.io/wundergraph/cosmo/router:latest
          ports:
            - containerPort: 3002
          env:
            - name: GRAPH_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cosmo-secret
                  key: GRAPH_API_TOKEN
            - name: CONTROLPLANE_URL
              value: "http://cosmo-controlplane.cosmo.svc.cluster.local:3001"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
