apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: task-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: ghcr
        property: dockerconfigjson
