resources:
  - deployment.yaml
  - service.yaml
  - appService.yaml
  - ingress.yaml
  - externalsecret.yaml
  - externalsecret-ghcr.yaml
  - pgsqlDeployment.yaml
  - pgsqlService.yaml
  - pvc.yaml

images:
  - name: ghcr.io/pestana1213/manager
    newTag: e5ff16dbeba1aca569933f035586b17a8b1d8781
