resources:
  - deployment.yaml
  - appService.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - externalsecret.yaml
  - externalsecret-ghcr.yaml
  - pgsqlDeployment.yaml
  - pgsqlService.yaml
  - pvc.yaml

images:
  - name: ghcr.io/pestana1213/manager
    newTag: 16c0bc6b058fa9249c7ca1db4f681c86fcddff7f
  - name: ghcr.io/pestana1213/task-manager-web
    newTag: latest
