resources:
  - deployment.yaml
  - appService.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - externalsecret.yaml
  - externalsecret-ghcr.yaml
  - pgsqlDeployment.yaml
  - pgsqlService.yaml
  - pvc.yaml

images:
  - name: ghcr.io/pestana1213/manager
    newTag: 9a72b2f1ce68ea2775a13fbe7b9dc6ef03b69351
  - name: ghcr.io/pestana1213/task-manager-web
    newTag: latest
