apiVersion: v1
kind: Secret
metadata:
  name: controlhub-db-secret
  namespace: task-manager
type: Opaque
data:
  POSTGRES_DB: Y29udHJvbGh1Yg==      
  POSTGRES_USER: Y29udHJvbGh1Yg==    
  POSTGRES_PASSWORD: c3Ryb25ncGFzc3dvcmQ=
