apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: immich-secret
  data:
    - secretKey: db-password
      remoteRef:
        key: immich
        property: db-password
