apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "26.1"
            - name: MEMORY
              value: "4G"
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data