apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  serviceName: minecraft-service
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "26.1"
            - name: MEMORY
              value: "4G"
            - name: MOTD
              value: "§aGolias SMP §r| §bSurvival"
            - name: DIFFICULTY
              value: "normal"
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi