apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wealth-service-db
  namespace: wealth-service

spec:
  refreshInterval: 24h

  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: wealth-service-db
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: wealth-service/database
        property: username

    - secretKey: password
      remoteRef:
        key: wealth-service/database
        property: password
