resources:
  - namespace.yaml
  - external-secret.yaml
  - external-db-secret.yaml
  - pvc.yaml
  - postgres.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml

images:
  - name: ghcr.io/pestana1213/wealth-service
    newTag: 6ef3990e26d518327dced8c414f83df8ade1419f
  - name: ghcr.io/pestana1213/wealth-frontend
    newTag: 06e285b2e0b2cb9643b96a658a0287f25697302c
