resources:
  - namespace.yaml
  - external-secret.yaml
  - external-db-secret.yaml
  - pvc.yaml
  - postgres.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml
  - hpa.yaml

images:
  - name: ghcr.io/pestana1213/wealth-service
    newTag: c20adbe7a57bf5e77f9268d232f1d29935da9a38
  - name: ghcr.io/pestana1213/wealth-frontend
    newTag: d31ee1b0000bc14a9c1cfd6d050f1a1b97fbdda6
