apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wealth-frontend
  namespace: wealth-service
  labels:
    app.kubernetes.io/name: wealth-frontend
    app.kubernetes.io/instance: wealth-frontend
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - wealth
  rules:
    - host: wealth
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wealth-frontend
                port:
                  name: http
