apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-metrics
  namespace: homelab-metrics
  labels:
    app: homelab-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-metrics
  template:
    metadata:
      labels:
        app: homelab-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      hostPID: true
      hostNetwork: true
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: homelab-metrics
          image: ghcr.io/pestana1213/rack-metrics
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: HOMELAB_MQTT_BROKER_URL
              value: "tcp://192.168.1.225:31719"
            - name: HOMELAB_METRICS_DISK_PATH
              value: "/"
            - name: HOMELAB_METRICS_PUBLISH_INTERVAL_MS
              value: "5000"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
