resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - externalsecret.yaml

images:
  - name: ghcr.io/pestana1213/rack-metrics
    newTag: b664e4f7f0d65eb8fa6b27c2bbe449489cf0acba
