apiVersion: v1
kind: Service
metadata:
  name: homelab-metrics
  namespace: homelab-metrics
  labels:
    app: homelab-metrics
spec:
  selector:
    app: homelab-metrics
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
