apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homelab-metrics
  namespace: homelab-metrics
spec:
  selector:
    matchLabels:
      app: homelab-metrics
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
