apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-hub-db
  namespace: control-hub
spec:
  refreshInterval: 24h

  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: control-hub-db
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: control-hub/database
        property: username

    - secretKey: password
      remoteRef:
        key: control-hub/database
        property: password
