apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-hub
  namespace: control-hub
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - control-hub
  rules:
    - host: control-hub
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: control-hub
                port:
                  number: 8080
