resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - external-secret.yaml
  - postgres.yaml
  - postgres-service.yaml
  - pvc.yaml
  - external-db-secret.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml
images:
  - name: ghcr.io/pestana1213/control-hub
    newTag: 42dad7bc0a8516454589f6fd9231e86197137d2e
  - name: ghcr.io/pestana1213/golias-web
    newTag: latest
