resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - external-secret.yaml
  - postgres.yaml
  - postgres-service.yaml
  - pvc.yaml
  - external-db-secret.yaml
images:
  - name: ghcr.io/pestana1213/control-hub
    newTag: 6374277b7f2a029dbcae2c511ab1f528f30cdc84
