resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - external-secret.yaml
  - postgres.yaml
  - postgres-service.yaml
  - pvc.yaml
  - external-db-secret.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml
  - web-servicemonitor.yaml
images:
  - name: ghcr.io/pestana1213/control-hub
    newTag: 23ad00f492d45d700c43f506410c9c2f933e7a6b
  - name: ghcr.io/pestana1213/golias-web
    newTag: d4d5540a81c6258170c99e5883f1f06e61144308
