apiVersion: apps/v1
kind: Deployment
metadata:
  name: golias-web
  namespace: control-hub
  labels:
    app.kubernetes.io/name: golias-web
    app.kubernetes.io/instance: golias-web
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: golias-web
      app.kubernetes.io/instance: golias-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: golias-web
        app.kubernetes.io/instance: golias-web
        app.kubernetes.io/component: frontend
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: golias-web
          image: ghcr.io/pestana1213/golias-web
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
