---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      valuesObject:
        injector:
          enabled: false
        server:
          standalone:
            enabled: true
          dataStorage:
            enabled: true
            size: 10Gi
          ui:
            enabled: true
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-tailscale-ingress
  namespace: vault
  annotations:
    tailscale.com/hostname: vault
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - vault
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-helm
                port:
                  number: 8200
